config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="space-4"></div>
<div class="text-center">
  <%= form_for(@contact) do |f| %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
      <% if @contact.errors.any? %>
      <div id="error_explanation" class="text-center">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="biggest">
        <div class="field">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name, class: "form-control text-center normal height_40" %>
        </div>
        <div class="field">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name, class: "form-control text-center normal height_40" %>
        </div>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: "form-control text-center normal height_40" %>
        </div>
        <div class="field">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: "form-control text-center normal height_40" %>
        </div>
      </div>
    </div>
  </div>
  <div class="space-10"></div>
  <div class="actions">
    <%= f.submit class: "btn btn-success biggest" %>
  </div>
<% end %>
</div>

app/views/contacts/edit.html.erb
<div class="bigger">
  <h1 class="text-center huge sketch">Editing Contact</h1>
</div>

<%= render 'form' %>

<div class="text-center">
<%= link_to 'Back', contacts_path, class: "text-center btn btn-primary biggest" %>
</div>

<div class="space-30"></div>

app/views/contacts/index.html.erb
<p id="notice text-center"><%= notice %></p>
<div class="space-10"></div>

<div class="biggest">
<h1 class= "text-center sketch huge">Address Book</h1>
</div>

<table class="table table-striped table-hover biggest">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="penpal">
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.address %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact), class:"btn btn-warning min_100 small" %></td>
        <td><%= link_to 'Destroy', contact, class:"btn btn-danger min_100 small", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
  <%= link_to 'New Contact', new_contact_path, class: "biggest btn btn-success pull-right" %>
</div>
</div>

app/views/contacts/new.html.erb
<div class="bigger">
  <h1 class="text-center huge sketch">New Contact</h1>
</div>


<%= render 'form' %>

<div class="text-center">
<%= link_to 'Back', contacts_path, class: "text-center btn btn-primary biggest" %>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="penpal">

<div class= "container-fluid">
<%= yield %>
</div>

</body>
</html>